### ISSUE TITLE
The auto-numbering of child objects is fooled by the `+=` operator

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/pySBOL3#100]
When `+=` is used to add to a list, as can be done when adding SubComponents to Component.features, both `insert` and `set` are called. Objects on the list go through the auto-numbering twice as a result.

Pass the added object along to the Identified.counter_value so that if an object is already in the list it does not get renumbered.

**Comment by jakebeal** [comment]
I need to add some objects incrementally. Is there a recommended workaround?

Right now my code looks like:
```
provision_LUDOX = paml.PrimitiveExecutable()
protocol.hasActivity += {provision_LUDOX}
# do some things
provision_ddH2O = paml.PrimitiveExecutable()
protocol.hasActivity += {provision_ddH2O}
```

**Comment by tcmitchell** [comment]
`protocol.hasActivity.append(provision_ddH2O)` is probably the most natural workaround.
