### ISSUE TITLE
Consider adding createAbc methods 

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/pySBOL3#102]
Other libraries construct objects by calling `createType` on the parent. For instance, one might call `Component.createSubComponent` to construct a child SubComponent on a Component.

The lack of these `createAbc` methods caused some consternation among a small number of participants at [COMBINE 2020](http://co.mbine.org/events/COMBINE_2020).

**Comment by jakebeal** [comment]
It seems to me that these are all essentially macros for "create and add". If we add them, I don't think they do any harm, but they are a large number of almost-empty methods that we have to maintain.  Is that a problem? Also, is there a more pythonic way to go?

Some ideas:
- Allow a user to specify where the object is getting added as an optional argument.
- When you add an object (e.g., an interaction), it automatically adds all of the other non-TopLevel objects that it points to (both child to TopLevel and TopLevel to document).

I don't have particularly strong feelings here, and this certainly isn't required for a beta release.

**Comment by bbartley** [comment]
Currently we use `append` which essentially does the same thing as `createAbc` as far as I can tell.  And `append` is what will feel natural to Python users.

**Comment by jakebeal** [comment]
We have been accumulating wrapper functions of this sort in SBOL-utilities. If specific additional ones are desired, issues should be opened there.
