### ISSUE TITLE
Copy/clone methods

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#123]
A request for methods that clone or copy objects, coming from OPIL user:
https://github.com/SD2E/opil/issues/50

**Comment by bbartley** [comment]
Have been experimenting with this.  One challenge is that `copy` methods need access to object builder functions which are stored as static attributes in the `Document` class.  Unfortunately they can't be imported without causing circular imports.

Some possible workarounds.
- expose builder functions for each class, so instead of calling a constructor, e.g. `Component()` we might call `Component.builder()`
- instead of `copy = target_obj.copy()` we might have `copy = doc.copy(target_object)`, although that seems a little clumsy

**Comment by tcmitchell** [comment]
I'm not sure why `copy` methods need access to object builder functions. Shouldn't copy methods call the constructor and have the knowledge of which properties are required and thus how to invoke the constructor? This assumes that each class gets a copy method or relies on one via inheritance.

If you really want to use the builder functions, I don't understand why the storage of builders as a static attribute is a problem. You can get to them just fine, although it would really want to be prettied up if we're going to expose this API:

```python
>>> c_copy = sbol3.Document._uri_type_map[sbol3.SBOL_COMPONENT]('https://github.com/synbiodex/pysbol3/foo')
>>> c_copy
<sbol3.component.Component object at 0x7fc05885a8b0>
>>> c_copy.identity
'https://github.com/synbiodex/pysbol3/foo'
>>> c_copy.display_id
'foo'
```

The above creates a hollow instance, then it would have to be populated, so invocation of the builder is not sufficient, just one path to get an instance.

**Comment by bbartley** [comment]
> Shouldn't copy methods call the constructor and have the knowledge of which properties are required and thus how to invoke the constructor? This assumes that each class gets a copy method 

I'm starting from a different assumption.  Ideally, the `copy` method should only be implemented once on a base class such as `SBOLObject` or `Identified`.  Otherwise, every new class will require a specialization of the `copy` method.  This just makes for more code to maintain as well as adding extra burden for users who want to define extension classes.  It follows then that the `copy` method should be agnostic about which properties are required, and fill in the property values after object creation, using a builder pattern similar to the `doc.read` method.  

> If you really want to use the builder functions, I don't understand why the storage of builders as a static attribute is a problem. You can get to them just fine, although it would really want to be prettied up if we're going to expose this API

It's the circular import that is an issue.  This is what happens (some code elided for brevity):
```
from .document import Document

class SBOLObject:

    def copy(self, target_doc=None, target_namespace=None):

        new_uri = self.identity
        new_obj = sbol3.Document._uri_type_map[type_uri](name=new_uri, type_uri=self.type_uri)
```

Results in:
```
Traceback (most recent call last):
  File "test/test_identified.py", line 7, in <module>
    import sbol3
  File "/Users/bbartley/Dev/git/pySBOL3/sbol3/__init__.py", line 8, in <module>
    from .object import SBOLObject
  File "/Users/bbartley/Dev/git/pySBOL3/sbol3/object.py", line 6, in <module>
    from .document import Document
  File "/Users/bbartley/Dev/git/pySBOL3/sbol3/document.py", line 18, in <module>
    class Document:
  File "/Users/bbartley/Dev/git/pySBOL3/sbol3/document.py", line 22, in Document
    builder: Callable[[str, str], SBOLObject]) -> None:
NameError: name 'SBOLObject' is not defined
```

**Comment by tcmitchell** [comment]
One option would be to move the builder functions to class methods. There were a couple of these originally before I settled on making them functions. The functions allowed me to make the builders internal only, and not part of the public API. Methods feel more accessible, whether they have a leading underscore or not.

Another option would be to go behind the curtain and locate the Document class at runtime. This is messy, and may not work in all cases, but appears to work in a test environment:

```python
    def doc_class(self):
        my_module = sys.modules[globals()['__package__']]
        doc_class = my_module.Document
        return doc_class
```

Yet another option is to have OPIL generate a target instance by calling the builder, and then pass that target instance to the copy method as the target of the copy. Then the copy method doesn't need to construct the new instance. This would want a better API on Document to create an instance based on a class URI. It would unstick the OPIL use case, but not solve the eventual problem of copy/clone in sbol3.

And there's always creating a `copy()` method on each class that creates a new instance and then calls the `Identified.copy(target:Identified)` with that instance. I understand that you don't want this extra burden for users who want to define extension classes.

Do any of these options help? Or generate other ideas?

**Comment by tcmitchell** [comment]
@bbartley Can you point to a unit test that exercises `replace_namespace(old_uri, target_namespace, rdf_type)`? Because that function sure doesn't look like it will work. It has references to at least two symbols that do not exist in pySBOL3: `parseClassName` and `SBOL_TYPED_URIS`. And it references `URIRef` and does not import `rdflib`.

I think `replace_namespace` must have been lifted out of pySBOL2 and not updates for pySBOL3.

**Comment by bbartley** [comment]
It was lifted out of pySBOL2.  Since issue #132 was punted until later, the `replace_namespace` method has never been exercised.
