### ISSUE TITLE
Duplicating objects in the same Document not supported

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#131]
Cloning an object within a single Document is not supported by the current `copy` method because it will cause a URI collision when the new object is created.  However, in some cases it may prove helpful to `copy` objects within a `Document`

**Comment by bbartley** [comment]
This is needed for https://github.com/SD2E/opil/issues/142

**Comment by jakebeal** [comment]
URI collisions can be avoided if the only objects that are allowed to be cloned are TopLevel objects. If the user supplies a non-colliding UID for the top-level, then all of its children are changed as well. Also: the boundary of TopLevel + children is a natural boundary on cloning.

**Comment by tcmitchell** [comment]
Does cloning a top level create all new child objects? Sort of like copying a tree by cloning the root, then copying all the children?

If so, we could add `TopLevel.clone(new_identity)` and then traverse the object hierarchy copying all of the properties and child objects. That feels tractable. Are there any gotchas I'm not thinking of?

**Comment by bbartley** [comment]
I think the current `copy` method does recursively copy all child objects in the manner you describe.  I can think of two gotchas when cloning objects within the same `Document`.  The first is avoiding URI collisions, as noted above.  The second is mapping object references...for example, within a `Component` object tree, there might be child `Constraints` that reference `SubComponents`, and these references must be mapped correctly into the new object tree when performing the copy (or else they will reference back to the original objects that were cloned)

**Comment by tcmitchell** [comment]
I have addressed this with `TopLevel.clone()`. It is important to note that the resulting clone returned by `TopLevel.clone()` _is not in the document_. The clone must be added to the document by the programmer as a separate step.

For example:
```python
# get a component out of the document
c = doc.find('https://github.com/synbiodex/pysbol3/comp1')

# clone the component
new_identity = 'https://github.com/synbiodex/pysbol3/comp2'
clone = c.clone(new_identity)

# Add the clone to the document
doc.add(clone)
```
