### ISSUE TITLE
Copy objects into new namespaces

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#132]
It may be helpful to export and import `Documents` and other objects into new namespaces.  This is not supported with current `copy` methods

**Comment by tcmitchell** [comment]
Note to implementer: The function `replace_namespace(old_uri, target_namespace, rdf_type)`, in object.py, does not work in pySBOL3. It was lifted out of pySBOL2 and not updated for pySBOL3. For example, `replace_namespace` calls `parseClassName`, which does not exists, references `SBOL_TYPED_URIS`, which also does not exist, and references `URIRef` without importing rdflib.

**Comment by tcmitchell** [comment]
The newly added `sbol3.copy` does this. Call it like this:

`sbol3.copy(objects, into_namespace='https://example.org/your_namespace')`

I think this issue is covered with the most recent changes.
