### ISSUE TITLE
Should CustomTopLevel constructor require the identity parameter

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#142]
Currently `identity` has a default value of `None`.  This means it is possible to create a `CustomTopLevel` object with no URI which could turn out to be a problem.  Is there a reason why that is allowed (maybe it is initialized to None in case the constructor is called as a builder method)?

**Comment by tcmitchell** [comment]
I think `identity` has a default value of `None` to turn it into a keyword argument. I agree that we don't really want to let that travel too far before flagging it as an error.

I think it is the case that all `TopLevel` instances _must_ receive an `identity` argument (either full URI or display ID). So maybe we need to add a check in the `TopLevel` constructor to ensure that there is a value.

**Comment by bbartley** [comment]
> So maybe we need to add a check in the TopLevel constructor to ensure that there is a value.

That sounds ideal to me as well.
