### ISSUE TITLE
CustomTopLevel inherits measures attribute

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#143]
This might actually be a spec issue rather than software issue.  `CustomTopLevel` inherits a `measures` attribute from `TopLevel`.   Do we want to assume that every top level annotation class should have this attribute?

**Comment by tcmitchell** [comment]
`TopLevel` inherits the `measures` property from `Identified`. The SBOL 3 specification says that `Identified` has a `hasMeasure` (translated to `measures` in this library) property. I don't think we have any latitude here if we're going to implement the spec.

Is the `measures` property causing issues for you?

**Comment by bbartley** [comment]
Then this is a spec issue, but would be good to discuss amongst ourselves before I post an issue [on the other repo](https://github.com/SynBioDex/sbol-specification)

In the context of OPIL it just pollutes the namespace in a confusing manner -- we have classes `Measurement`, `MeasurementType`, and `Measure`.  The way these are all linked to one another is already complicated enough -- then because of the inheritance of an extraneous `measures` attribute, things can get _really_ confusing

Also, as a matter of principle, I'm not sure that we should assume that everyone who wants to define an SBOL extension class will want the `measures` attribute.

**Comment by bbartley** [comment]
Also the `sbol3.Measures` inherits the `measures` attribute which might point to even more `Measures`.  It's `Measures` all the way down.

**Comment by jakebeal** [comment]
Shouldn't it be `hasMeasure` and not measures?  It's inherited all the way from `Identified`, so it should be universal in objects being used in the SBOL namespace.  Some just won't use it, but we thought it was better to make it universal than to have a list of most of the classes.

**Comment by jakebeal** [comment]
Plan:

 - @bbartley will open an SBOL spec issue to consider whether hasMeasure should be inherited to imported objects
 - @bbartley will open an OPIL issue about whether Measure words over there ought to be something different like Assay.

**Comment by jakebeal** [comment]
Closing as a spec issue in https://github.com/SynBioDex/SBOL-specification/issues/460
It can be recreated if the spec changes.
