### ISSUE TITLE
Are required properties checked?

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#165]
I was skimming through the code, and it looked like properties that have a minimum cardinality of 1 (i.e., required properties) are not currently checked.  This could be a first step in implementing the validation rules.

**Comment by tcmitchell** [comment]
I will quibble and say that [sometimes bounds are checked](https://github.com/SynBioDex/pySBOL3/blob/master/sbol3/property_base.py#L61-L64). But in fact, I think your statement is largely true. For instance, properties that have a minimum of 1 value, but a maximum cardinality greater than 1, like Component.type, are not bounds checked on set/get. Although they could be by mimicking the linked example in SingletonProperty.

I agree, this would make a good early validation case.
