### ISSUE TITLE
Add traversal method to Document and Identified

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/pySBOL3#169]
Add a method to both Document and Identified that will allow a user to pass a function that will be invoked on every object contained in the Document or the Identified. In the case of Identified, that means all child, or owned, objects.

**Comment by tcmitchell** [comment]
Consider the [visitor pattern](https://en.wikipedia.org/wiki/Visitor_pattern). `Document.validate()` could be recast in terms of such a traversal function.

**Comment by jakebeal** [comment]
We'll likely want to have filtered and dynamically ordered versions of this as well, e.g., invoke on all ExternallyDefined, invoke on all prov:Activities ordered by their relations
