### ISSUE TITLE
lookup() fails due to document not being set on child object

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#176]
When child objects are added, they get their identity, but don't get their document set. This will then cause lookup to fail when run on such an object.
Here is a minimal example of a failure to set identity:

```
import sbol3

doc = sbol3.Document()
sbol3.set_namespace('https://bioprotocols.org/paml/primitives/')

c = sbol3.Component("scratch",sbol3.SBO_DNA)
doc.add(c)
lsc = sbol3.LocalSubComponent(sbol3.SBO_DNA)
c.features += {lsc}

```

**Comment by tcmitchell** [comment]
This could be the type of case that was the root cause of #104. Also note that `+=` is known to not work properly (#100), but the test case above demonstrates the failure to set the document when using `c.features = [lsc]`.

**Comment by tcmitchell** [comment]
How/where is `lookup()` being used in this example? `LocalSubComponent` looks like it does not have any referenced objects, and lookup works with referenced objects. Could you post a more complete example that includes `lookup()`?

Failing that, this is a valid issue for the failure to set the document on a child object, but that would be unrelated to lookup.

**Comment by jakebeal** [comment]
If you add these further lines, it will throw an error due to the document not being set:

```
int = sbol3.Interaction(sbol3.SBO_DEGRADATION)
c.interactions.append(int)
p = sbol3.Participation(sbol3.SBO_REACTANT,lsc)
int.participations.append(p)
p.participant.lookup()
```

**Comment by jakebeal** [comment]
This is cropping up again in another context. Here, the document information appears to be going missing from some Feature objects. A reproducible case is running this script: https://github.com/iGEM-Engineering/iGEM-distribution/blob/7535d6295ac4dea0a155250bc7bb9242c7374690/scripts/build_distribution.py with line 16 commented out

**Comment by tcmitchell** [comment]
@jakebeal This is not easily recreated at the moment because build_distribution depends on sbol_utilities and sbol_utilities depends on rdflib5 and the current sbol3 requires rdflib6. I think we're circular in our dependencies at this particular point in time. This should get cleaned up with SynBioDex/SBOL-utilities#31 and then I should be able to take a look at it.

**Comment by jakebeal** [comment]
https://github.com/SynBioDex/SBOL-utilities/issues/31 has been resolved, but the new version is not yet released.
