### ISSUE TITLE
Child objects should error when their identity is reassigned

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#178]
There are a number of ways that a programmer can bungle child objects such that they get added in two places and thus have their identity reassigned. This causes things to break in all sorts of difficult to debug ways.

We should stop this early by having the name assignment process throw an error when the name is already set.

**Comment by jakebeal** [comment]
Note that this will require #100 to be resolved as well.

**Comment by bbartley** [comment]
As a result of #181 the following now results in `ValueError: Parameter already has identity http://strateos.com/param and cannot be re-parented.`
```
p = Parameter('param')
protocol.has_parameter = [p]
```
Are we sure this is the behavior we want?

**Comment by jakebeal** [comment]
That shouldn't be giving an error unless we made Parameter a TopLevel when we shouldn't have.

**Comment by tcmitchell** [comment]
What's a `Parameter`? What is the type or class of your `protocol` variable? What kind of property is the `has_parameter` property?

```python
>>> import sbol3
RDFLib Version: 5.0.0
>>> sbol3.Parameter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sbol3' has no attribute 'Parameter'
```

**Comment by jakebeal** [comment]
Parameter is an OPIL class. It should be a child class, and I see it's listed as an Identified. Not sure whether this problem is on the SBOL side or the OPIL side then... my guess is it's on the OPIL side.

**Comment by jakebeal** [comment]
Actually, I notice something else as well... @bbartley , Parameter is supposed to be an abstract class. Could that be playing in somehow as well?

**Comment by bbartley** [comment]
So, I think a related question is, do we always required that the identity of a child object will be automatically generated by the library and the user cannot assign their own display_id?

**Comment by jakebeal** [comment]
Yes, the user cannot assign their own display_id. That's a best practice from SBOL3, and I don't see any reason to let people violate it.

**Comment by bbartley** [comment]
Is this also true in the case of UUIDs?

**Comment by tcmitchell** [comment]
While there is some support for UUIDs in pySBOL3, I doubt it is complete and I suspect there are bugs. This is an area that may be buggy. Would you care to write some UUID-oriented unit tests? It might be a good idea if you are planning to use UUIDs in your application.

**Comment by jakebeal** [comment]
I consider UUIDs to be a 1.1-level support issue. Nobody who is currently using this library is using UUIDs.
