### ISSUE TITLE
Problem when auto-generating extension classes with required arguments

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#182]
I encountered a problem when auto-generating extension classes for OPIL.  More specifically, when autogenerating a class which derives from `CombinatorialDerivation`.  The issue is because `CombinatorialDerivation` has required arguments in the constructor.  The code generator has no way of knowing or inferring that `CombinatorialDerivation` has required arguments.  I can think of a couple of solutions to this problem, but they aren't simple.

Below is an example of how an extension class is hard-coded.  The part that is difficult for autogeneration is highlighted in the comments:
```
from sbol3 import CombinatorialDerivation, Document, IntProperty, set_namespace

class SampleSet(CombinatorialDerivation):

    def __init__(self, identity, template_component, replicates):
        CombinatorialDerivation.__init__(self, identity, template_component)
        self.replicates = IntProperty(self, 'http://bioprotocols.org/v1#replicates', 
                                      0, 1, None, replicates)

# Because pySBOL's parser can't use constructors with variable-length argument lists, we have to define
# a builder that fills in dummy values for required arguments.  Unfortunately, OPIL can't auto-generate a 
# builder, because it doesn't know that the superclass has required arguments
def build_sample_set(identity: str, *, type_uri: str = 'http://bioprotocols.org/v1#SampleSet'):
    replicates = 0
    template = PYSBOL3_MISSING
    return SampleSet(identity, template, replicates, type_uri=type_uri)

# Register builder method for Document parser
Document.register_builder('http://bioprotocols.org/v1#SampleSet', build_sample_set)

# Construct an example object, so we can verify round-tripping
set_namespace('http://bbn.com/synbio/')
doc = Document()
s = SampleSet('s', 'http://bbn.com/synbio/foo', 3)
doc.add(s)

# Roundtrip
doc2 = Document()
doc2.read_string(doc.write_string(file_format='turtle'), file_format='turtle')
assert(len(doc2.objects) == 1)
```

**Comment by tcmitchell** [comment]
The rationale for having required arguments to the constructor is to help programmers write correct programs. The required arguments match required properties as listed in the SBOL 3 specification. I am reluctant to abandon this philosophy.

I can't tell what you're asking for, or what change you are requesting. Is it that you want the parser to "use constructors with variable-length argument lists"? What would that look like?

At present the contract between the parser and the builder functions is that the parser will invoke the builder function with two arguments, an identity URI and a type URI. The builder function should return an instance that matches those specifications. The details of how that happens are up to the author of the builder function.

Are you suggesting a change to that contract? If so, can you elaborate on your proposed new contract?

Or are you suggesting that constructors (`__init__` methods) should have no required arguments?

**Comment by bbartley** [comment]
> I can't tell what you're asking for, or what change you are requesting.

Not advocating for any particular solution at the moment.  Any solution is going to involve significant amount of work, whether in pySBOL3 or in the factory part of OPIL.  Simply putting this on the table for discussion.

> The builder function should return an instance that matches those specifications. The details of how that happens are up to the author of the builder function.

Herein is the difficulty.  What if the author of the builder function is not a person, but rather the builder is autogenerated by the OPIL factory.  For example, consider an extension class `SampleSet` that extends `CombinatorialDerivation`.  There is no (straightforward) way for the OPIL factory to know in advance that `CombinatorialDerivation` has 1 required argument (i.e., `template`).  Therefore I cannot automatically generate a builder method that will call the CD constructor with a placeholder value inserted in place of the required argument.

**Comment by tcmitchell** [comment]
If the generator already knows about `CombinatorialDerivation` and other sbol3 classes, perhaps the generator could be taught about required arguments too. Or maybe the generator doesn't really know about `CombinatorialDerivation`, maybe the program or programmer who put together the data file that the generator is reading knows about `CombinatorialDerivation`.

Another alternative is the `inspect` module, with which you can inspect function and method signatures. Here's an example using the `CombinatorialDerivation` constructor:

```python
>>> import sbol3
RDFLib Version: 5.0.0
>>> 
>>> import inspect
>>> 
>>> inspect.signature(sbol3.CombinatorialDerivation.__init__)
<Signature (self, identity: str, template: Union[sbol3.component.Component, str], *, strategy: str = None, variable_features: List[str] = None, attachments: List[str] = None, name: str = None, description: str = None, derived_from: List[str] = None, generated_by: List[str] = None, measures: List[sbol3.object.SBOLObject] = None, type_uri: str = 'http://sbols.org/v3#CombinatorialDerivation') -> None>
>>> 
>>> 
>>> inspect.getfullargspec(sbol3.CombinatorialDerivation.__init__)
FullArgSpec(args=['self', 'identity', 'template'], varargs=None, varkw=None, defaults=None, kwonlyargs=['strategy', 'variable_features', 'attachments', 'name', 'description', 'derived_from', 'generated_by', 'measures', 'type_uri'], kwonlydefaults={'strategy': None, 'variable_features': None, 'attachments': None, 'name': None, 'description': None, 'derived_from': None, 'generated_by': None, 'measures': None, 'type_uri': 'http://sbols.org/v3#CombinatorialDerivation'}, annotations={'return': None, 'identity': <class 'str'>, 'template': typing.Union[sbol3.component.Component, str], 'strategy': <class 'str'>, 'variable_features': typing.List[str], 'attachments': typing.List[str], 'name': <class 'str'>, 'description': <class 'str'>, 'derived_from': typing.List[str], 'generated_by': typing.List[str], 'measures': typing.List[sbol3.object.SBOLObject], 'type_uri': <class 'str'>})
>>> 
```

**Comment by jakebeal** [comment]
I think that as long as we're consistent in SBOL3 with which arguments are required, that we should be able to match the inference in the SBOL3 RDF definition.

**Comment by bbartley** [comment]
I agree that's probably the way we want to go, but there are a couple of caveats.  First, the SBOL3 RDF definition will need to be updtated -- I'm not sure that SBOL3 ontology follows all the same OWL conventions as the OPIL ontology, and, at least at the moment, does not specify cardinality restrictions that make it possible to infer when a property value is required.  Second, in the case of constructor/builders with multiple required arguments, e.g., SampleSet, inferring the order of required arguments is not straightforward.

**Comment by tcmitchell** [comment]
As of the next release the constructor arguments can all be specified by keyword so there should be no need to infer the order of required arguments. This is a new change, see https://github.com/SynBioDex/pySBOL3/pull/174

The builder arguments are always just `identity` and `type_uri` and both can be specified by keyword as well. The parser invokes the builders with keyword arguments.

**Comment by jakebeal** [comment]
On the subject of the ontology... I think this will give us a good opportunity to tighten it up!

**Comment by jakebeal** [comment]
@bbartley , I'm assigning this to you since I think the proposed resolution is on the OPIL side.

**Comment by bbartley** [comment]
This appears to be working for supporting autogeneration as of https://github.com/SynBioDex/sbol_factory/commit/fd0dd32ae88d0b187df9d183a0669080e2131c68
