### ISSUE TITLE
Collection members are being readded to document

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#184]
Once a Collection is added to a document, when you add members to the collection with the append method, it tries to add them to the document, which causes an error if they are already in the document. Since Collection members are TopLevel objects, it should not be adding them, but should assume they are added elsewhere.

Minimal reproduction of this error:
```
import sbol3

doc = sbol3.Document()
sbol3.set_namespace('https://example.org')

execution = sbol3.Activity('protocol_execution')
doc.add(execution)

foo = sbol3.Collection('http://foobar.org/baz')
doc.add(foo)
foo.members.append(execution)
```

**Comment by jakebeal** [comment]
The same thing appears to be happening when adding a Sequence to `component.sequences`

An odd workaround, though: `foo.members.append(execution.identity)` does _not_ error.

**Comment by tcmitchell** [comment]
`Collection.members` and `Component.sequences` are both references. At present pySBOL3 makes an effort to automatically add the referenced objects to the document. It sounds like maybe it's trying too hard.

Your comment above, "it should not be adding them, but should assume they are added elsewhere", indicates that maybe pySBOL3 should not be adding these objects to the document at all. This would leave it in the hands of the programmer to ensure that referenced objects are added to the document. Is that a correct read of your statement?

**Comment by jakebeal** [comment]
The workflow question is linked to #102

What I'm finding that I'm doing is a pattern of:
- Create TopLevel, immediately add to document, or
- Create child object, immediately add to parent

That way, I don't run into problems with an object being referred to but not included because I forgot to include it.
SBOL has a strictly acyclic reference pattern, so it should never be necessary to wait before adding something into a document.  If we implement #102, then creating and adding will be linked.

In no case, however, do we want an object that _isn't_ a parent assuming that we want something to be added, like is happening here. This is because (1) we might have multiple references to an object, and (2) we might want to be referring to an object in a different document/context without automatically importing it.

**Comment by tcmitchell** [comment]
I chased down the origins of adding the referenced object to the document. This was included in the initial implementation of ReferencedObject properties, in https://github.com/SynBioDex/pySBOL3/pull/12. The commit specific commit was https://github.com/SynBioDex/pySBOL3/pull/12/commits/b7d9ea4ef6ee23533960cdd3c54fb30b110318c5.

This is an easy change to make, we'll just stop adding the referenced objects to the document.
