### ISSUE TITLE
Sequence encoding constants need to be updated for SBOL 3

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#185]
The sequence encoding constants SBOL_IUPAC_DNA and similar need to be updated for SBOL3.
They currently have the values from SBOL 2.
Their proper values can be found in Table 1

**Comment by tcmitchell** [comment]
The sequence encoding constants SBOL_IUPAC_DNA and similar match the [SBOL 3.0 specification](https://sbolstandard.org/docs/SBOL3.0specification.pdf).

These constants do not match the as yet unreleased 3.0.1 specification, which chose to change them, making them seem less "constant".

**Comment by jakebeal** [comment]
This was a change that was scheduled for 3.0 in March of 2019, per https://github.com/SynBioDex/SBOL-specification/issues/10 and https://github.com/SynBioDex/SBOL-specification/issues/191 
The table unfortunately wasn't correctly updated, and thus the fix.

**Comment by tcmitchell** [comment]
Three of the SBOL3 test suite examples will need updating as well:
* https://github.com/SynBioDex/SBOLTestSuite/tree/master/SBOL3/BBa_F2620_PoPSReceiver
* https://github.com/SynBioDex/SBOLTestSuite/tree/master/SBOL3/multicellular
* https://github.com/SynBioDex/SBOLTestSuite/tree/master/SBOL3/toggle_switch
