### ISSUE TITLE
Helper function to sanitize into display_id

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#191]
I've written a function to sanitize text into a legal display_id.

```
def string_to_display_id():
    display_id = name.strip().replace(" ","_").replace("-","_") # display id is name processed to comply with rules
    if display_id[0].isdigit(): display_id = "_"+display_id
    return display_id
```

Something like this helper function may be generally useful for turning names into display IDs. It would want to deal with a larger range of the non-allowed characters, however.

**Comment by jakebeal** [comment]
I have expanded this to a complete sanitization function that handles all non-allowed characters. I would suggest that this be added as a utility function:

```
def string_to_display_id(name):
    def sanitize_character(c):
        replacements = {' ': '_', '-': '_', '.': '_'}
        c = replacements.get(c, c)  # first, see if there is a wired replacement
        if c.isalnum() or c == '_':  # keep allowed characters
            return c
        else:  # all others are changed into a reduced & compatible form of their unicode name
            return f'_{unicodedata.name(c).replace(" SIGN","").replace(" ","_")}'

    # make replacements in order to get a compliant displayID
    display_id = "".join([sanitize_character(c) for c in name.strip()])
    # prepend underscore if there is an initial digit
    if display_id[0].isdigit():
        display_id = "_"+display_id
    return display_id
```

**Comment by tcmitchell** [comment]
I expected 'a:b' to convert to 'a_b' and instead it converts to 'a_COLONb'. Maybe that's ok, it was just a little surprising to me. Here are a couple of other tests I invented, how do these look to you, @jakebeal ?

```python
>>> sbol3.string_to_display_id('a:b')
'a_COLONb'
>>> sbol3.string_to_display_id('世界')
'世界'
>>> sbol3.string_to_display_id('Épée')
'Épée'
```

**Comment by tcmitchell** [comment]
Ah - I see. There are three special characters that get converted to underscore (`_`): space (` `), hyphen (`-`), and period (`.`). All other non-alphanumeric characters get converted to `_` followed by the name of the character, more or less.

Sometimes this is a bit surprising. For example, `'a/b'` converts to `'a_SOLIDUSb'`. And `'a\\b'` converts to `'a_REVERSE_SOLIDUSb'`.

**Comment by jakebeal** [comment]
For anything that should be converted to a more intuitive sequence, just add it to the `replacements` map. That would be good to do with :, /, and \ for example.

As for the other cases, I realize that I misunderstood the `isalnum` function, which I thought was a subset of `isascii`. If you replace `c.isalnum()` with `(c.isalnum() and c.isascii())` then I believe that should give the expected (if ugly) behavior.

**Comment by jakebeal** [comment]
Let me change my belief regarding the non-ASCII characters. I just checked and displayIDs do indeed allow them, so they don't need to be removed: '世界' and 'Épée' are OK.

Moreover, SBOL is supposed to start supporting IRIs in any case, just like everything else does these days, so I see no reason to prohibit them: https://github.com/SynBioDex/SBOL-specification/issues/369

We probably should add some test cases with these characters to the test set, however, to make sure that the other libraries can handle them as well.

**Comment by tcmitchell** [comment]
I agree. I've just been reading the spec and don't see any requirement for ASCII. I already have tests for `'世界'` and `'Épée'`.
