### ISSUE TITLE
Should there be a URI type or should URIs be handled as strings?

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#2]
In pySBOL2, a constructor may take either a full URI or a displayId as the first argument.  The library uses the `sbol_compliant_uris` Config.option to determine whether the argument should be interpreted as a displayId vs. a complete URI.  We'll have to do this differently in pySBOL3, because all URIs are required to be SBOL compliant, and besides that was a hack way of doing things anyway. 

One option would be to make a URI type so that the caller can make their intent explicit:
```
def __init__(self, identifier, required_argument_0, required_argument_1, rdf_type = foo):
    if type(identifer) is URI:
        do something else and treat the identifer as a URI
    if type(identifier) is str:
        do something and treat the identifier as displayId
```
The other option is to let the constructor infer whether the argument is a displayId or URI.
```
def __init__(self, identifier, required_argument_0, required_argument_1, rdf_type = foo):
    if string_has_uri_pattern(identifier):
        do something else and treat the identifer as a URI
    else:
        do something and treat the identifier as displayId
```
One could argue that this is less explicit, but perhaps simpler for the user (less verbose? the library figures out what the user meant to do?).

**Comment by tcmitchell** [comment]
All `TopLevel`s take a `name` as the first argument to the constructor. This `name` can be a full URI or a `display_id`. The library detects which it got by trying to parse `name` as a URL. If that succeeds and has a `scheme` ("http", "https", etc.), a  `netloc` (e.g. "example.com") and a `path` ("/", "/synbiodex/") as required in Section 5.1 of the SBOL 3.0 spec, then `name` is determined to be a URI and is the `identity` of the entity, and `display_id` is derived from that. 

If `name` does not pass the test as a URL, then `name` is interpreted as a `display_id` and appended to `sbol3.get_homespace()` to form the `identity`.

For example:

```python
>>> import sbol3
RDFLib Version: 5.0.0
>>> 
>>> sbol3.get_homespace()
'http://example.com/sbol3/'
>>> 
>>> c1 = sbol3.Component('https://github.com/synbiodex/pysbol3/c1', sbol3.SBO_DNA)
>>> c1.identity
'https://github.com/synbiodex/pysbol3/c1'
>>> c1.display_id
'c1'
>>> 
>>> c2 = sbol3.Component('c2', sbol3.SBO_DNA)
>>> c2.identity
'http://example.com/sbol3/c2'
>>> c2.display_id
'c2'
>>> 
```

**Comment by tcmitchell** [comment]
After discussion with @bbartley and @jakebeal we have decided that this issue is essentially complete.
