### ISSUE TITLE
How to encode temperatures for a measurement?

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/pySBOL3#203]
I want to represent a list of timepoints values to describe the time intervals when a measurement is performed using the sbol3 data model. @jakebeal recommended a temporary solution where I create a `VariableFeature` to encode the time interval values and assign this object to a media `CombinatorialDerivation` object. I'm not sure if this was the best way to encode this information and would like to know how this information should be encoded in the current version of the pysbol3 library.

**Comment by jakebeal** [comment]
If you are specifying a list of measurement times for OPIL, you shouldn't need to use a kludge. An `opil:Measurement` has a property `opil:time` that takes any number of `om:Measure` objects.

If you don't believe this will work for your case, can you please explain in more detail exactly what you are trying to encode?

**Comment by tramyn** [comment]
That's my confusion. I meant temperatures. I have a list of temperature values with units that used in a measurement. Intent Parser encodes this information using CombinatorialDerivation objects. We discussed that the values for temperatures are represented using opil.Measure and added to a combinatorialDerivation as a variableFeature. The template of a combinatorialDerivation, however, points to a media template. Is this solution still the best way of encoding temperatures ? 

Also, I am going to move this issue over to opil since Intent Parser will need to interpret this type of information as opil.SampleSet rather than using sbol3.CombinatorialDerivations.
