### ISSUE TITLE
Copy Document

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#211]
Feature request cross-posted from OPIL repo:
https://github.com/SD2E/opil/issues/164

**Comment by tcmitchell** [comment]
I think this is complete between `Document.copy` and `copy`. 

`Document.copy` copies a `Document` into a newly created `Document` and returns the newly created `Document.

`copy` is more powerful. It can also change the namespace of the copied objects, and optionally ad the objects to an existing `Document`. The signature is:

`sbol3.copy(top_levels: Iterable[TopLevel],  new_namespace: Optional[str] = None,  new_document: Optional[Document] = None)`

A `Document` is an `Iterable[TopLevel]`, so you can pass an existing `Document` to `sbol3.copy` to copy the entire `Document`.

**Comment by tcmitchell** [comment]
Fixed in https://github.com/SynBioDex/pySBOL3/commit/f2acc5a4d0e6a3d93a1df1412ebaba0610d6e26e
