### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by abamaj** [SynBioDex/pySBOL3#216]
**I've created a VENV in jupyter noteboots to develop with with pySBOL3. When working alongside the documentation, I attempted to run this line of code:**

```
import pprint
pprint.pprint(sorted(c1a.properties))

```

**For some reason, this error occured:** 

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-29-1abcc969268e> in <module>
      1 # import pprint
      2 # pprint.pprint(sorted(c1a.properties))
----> 3 for items in c1a.properties:
      4     print(items)

~/Documents/Documents/AJenvs/pysbol3/lib/python3.8/site-packages/sbol3/object.py in __getattribute__(self, name)
     33     def __getattribute__(self, name):
     34         # Call the default method
---> 35         result = object.__getattribute__(self, name)
     36         if hasattr(result, '_sbol_singleton'):
     37             result = result.get()

AttributeError: 'Component' object has no attribute 'properties'
```

**How can this be fixed?**

**Comment by tcmitchell** [comment]
Sorry about that. The documentation and the library releases are a little out of sync. The `properties` attribute will be in the next alpha release, 1.0a8. Here's me using the latest (unreleased) code:

```python3
>>> import sbol3
RDFLib Version: 5.0.0
>>> c1 = sbol3.Component('http://example.org/pysbol3/c1', sbol3.SBO_DNA)
>>> c1.properties
['http://sbols.org/v3#displayId', 'http://sbols.org/v3#name', 'http://sbols.org/v3#description', 'http://www.w3.org/ns/prov#wasDerivedFrom', 'http://www.w3.org/ns/prov#wasGeneratedBy', 'http://sbols.org/v3#hasAttachment', 'http://sbols.org/v3#type', 'http://sbols.org/v3#role', 'http://sbols.org/v3#hasSequence', 'http://sbols.org/v3#hasModel']
>>> sbol3.__version__
'1.0a8'
```

If you want you can install the very latest code using `pip install git+git://github.com/synbiodex/pysbol3.git`, otherwise you'll have to wait for version 1.0a8 to be released (which should be a matter of days).

**Comment by tcmitchell** [comment]
`Identified.properties` was added in #194

**Comment by tcmitchell** [comment]
1.0a8 has been released. You should now be able to access the `properties` attribute on all SBOL objects. Please update your installation of pySBOL3 and try this out again.

I'm going to close this issue. If you have any trouble using `properties` please reopen the issue and add a comment to tell me about it.

Thanks again for the report!
