### ISSUE TITLE
More distinctive names for copy vs. clone?

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#225]
Copy and clone are typically used as synonyms, but they behave very differently in pySBOL (moving to a new document vs. making a twin with a new name).

**Comment by tcmitchell** [comment]
I'm pretty comfortable with the way things have landed. The two are indeed very similar.

`sbol3.copy` is intended to be the overarching method for copy and clone. `sbol3.copy` will return clones if no `into_namespace` or `into_document` arguments are used. Adding one or both of those arguments modifies the clones to either change their namespace(s) or add them to a `Document`. So I think I user will largely be directed to `sbol3.copy` and `clone` takes a back seat.

**Comment by tcmitchell** [comment]
I'm closing this out, but please reopen if you think we need to take another look at terminology.
