### ISSUE TITLE
Filetype to extension converter

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#244]
I'm finding it useful to have a table converting file types (which are defined via constant) into the corresponding extensions. This would be good to bundle into the library (maybe a  tablein the constants? maybe as a function?), rather than have it rewritten in many places.

````
type_to_standard_extension = {
    sbol3.SORTED_NTRIPLES: '.nt',
    sbol3.NTRIPLES: '.nt',
    sbol3.JSONLD: '.json',
    sbol3.RDF_XML: '.xml',
    sbol3.TURTLE: '.ttl'
}
````

**Comment by tcmitchell** [comment]
This might be useful as `Document.file_extension(file_format)` since it is bound to the reading and writing of documents. Given a desired `file_format`, `Document.file_extension()` would return the appropriate file extension.
