### ISSUE TITLE
Consolidate and harmonize ontology & SHACL

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#249]
There are multiple copies of the SBOL Ontology, in https://github.com/dissys/sbol-owl and https://github.com/SynBioDex/sbol_factory and in this repository as well. 

All of these should be using a single copy of the ontology, which is shared between them, also likely including the SHACL rules.

**Comment by tcmitchell** [comment]
* https://github.com/dissys/sbol-owl was last updated March 25, 2019, so it probably represents SBOL2, and not yet SBOL3.
* https://github.com/SynBioDex/sbol-shacl has a modified copy of the SBOL3 ontology from https://github.com/SynBioDex/sbol_factory

Ultimately, https://github.com/SynBioDex should probably be the keeper of the ontology either in its own repository or in the [specification repository](https://github.com/SynBioDex/SBOL-specification)

**Comment by jakebeal** [comment]
Unless there's a reason not to, I would be inclined to put it into the specification repository.  That's the direction we've taken with the SBOL Visual specification, which is allowing us to autogeneration portions of the specification and being quite useful.

**Comment by tcmitchell** [comment]
* The SBOL3 ontology has been published to https://github.com/SynBioDex/sbol-owl3
* The canonical SHACL rules still reside at https://github.com/SynBioDex/sbol-shacl
   * These are a copy of the rules in sbol-shacl, which in turn are generated from the full ontology in sbol-owl3
