### ISSUE TITLE
Revisiting default namespace

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#254]
Revisiting issue #99 based on discussions in the protocol representation retreat, I believe that we should reverse this decision and allow a default namespace, which is used until `set_namespace` is called.

User of the default namespace should be discouraged, but it seems likely to play a valuable role in helping people up the learning curve and allowing simpler experimentation with objects.

To make this work well, I think the implementation should include:
- The default namespace shouldn't be "example.org", but something that says clearly that this is the default unspecified namespace. Maybe `http://sbols.org/unspecified_namespace/`?
- A warning the first time that something is created using the unspecified namespace.

**Comment by tcmitchell** [comment]
This is a straightforward change. The logic for handling the namespace is in `SBOLObject._make_identity` in object.py.
