### ISSUE TITLE
SBOL2 and SBOL3 interoperability

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/pySBOL3#285]
I believe Tom found that pySBOL3 says the attached file is invalid, since the URI form is not as expected for SBOL3 objects.  You can do a search and replace of “/1” with “” to fix this.  The additional SBOL2 fields in the SBOL3 objects should not be causing any issues (Tom: please check), and the existence of an SBOL2 Collection in the file should not be a problem either (Tom: please check).  Technically, even the URI form should be a warning and not an error, I believe.  All of these issues can likely be post-processed out, if needed.  In any case though, Tom and I did discuss that the libraries need to be able to support files that mix SBOL2 and SBOL3 content, since this is perfectly legal RDF.

[test_collection-12.zip](https://github.com/SynBioDex/pySBOL3/files/6879792/test_collection-12.zip)

**Comment by tcmitchell** [comment]
@cjmyers is it ok to close out this issue?

**Comment by cjmyers** [comment]
Yes
