### ISSUE TITLE
Check for URI formatting

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#291]
Through a bug, I created a Component with the URI: 
`https://pubmed.ncbi.nlm.nih.gov/https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4899833`

I believe this is is technically a valid URI, but it's not a valid SBOL URI, and we should make sure to exclude such things.

**Comment by tcmitchell** [comment]
Why do you think `https://pubmed.ncbi.nlm.nih.gov/https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4899833` is not a valid SBOL URI?

**Comment by jakebeal** [comment]
Ugh... you are right... we don't actually constrain the contents of the [namespace] or [local] components at all. So yes, it's nonsensical, but it's legal, and there's probably actually use cases involving redirections or such for which this may even be appropriate...
