### ISSUE TITLE
Use snake case instead of camel case..?

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#3]
pySBOL used camel case for SBOL properties and methods.  This was partly to mirror the specification document closely and is also the convention used most commonly in RDF specifications.  However, camel case is not stylistically preferred in Python and might make some users uncomfortable.  Should we use snake case this time?

**Comment by tcmitchell** [comment]
We are using snake case. This is a Python library and should use symbols familiar to Python programmers.
