### ISSUE TITLE
Unprotect sbol3.Identified._extract_display_id?

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#310]
I have recently used the protected function `sbol3.Identified._extract_display_id` several times.
This seems like a useful utility; is there a reason to keep it protected?

**Comment by tcmitchell** [comment]
If `sbol3.Identified._extract_display_id` were to be made public, it needs to be carefully documented so user's know what they're getting into when they use it. I have no objection to making `sbol3.Identified._extract_display_id` public. We can consider whether it should remain a static method of `Identified`, or if it should be a top level function of `sbol3` (i.e. `sbol3.extract_display_id`).

**Comment by jakebeal** [comment]
I'm essentially using it as a helper function, so I'd be find with either place.
