### ISSUE TITLE
Update SBOL_INLINE and SBOL_REVERSE_COMPLEMENT to new URIs

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/pySBOL3#312]
See SynBioDex/SEPs#111

**Comment by tcmitchell** [comment]
Support for `SO_FORWARD` and `SO_REVERSE` were added in PR #327. I think we should leave `SBOL_INLINE` and `SBOL_REVERSE_COMPLEMENT` as they are since they are allowed and programs may want to make explicit checks for the URLs they represent. This means that there is no work to do on this issue.

**Comment by jakebeal** [comment]
Given that there is a SHOULD relation, would it be appropriate to mark `SBOL_INLINE` and `SBOL_REVERSE_COMPLEMENT` as deprecated, or otherwise encourage people away from them?

**Comment by tcmitchell** [comment]
> would it be appropriate to mark SBOL_INLINE and SBOL_REVERSE_COMPLEMENT as deprecated

We could, and I considered that. But it's not as easy as marking a function as deprecated. See https://www.scrygroup.com/tutorial/2019-06-27/module_level_deprecations/

That seemed heavyweight enough that I was reluctant to do it. We absolutely can though. Let me know your thoughts @jakebeal

**Comment by jakebeal** [comment]
That seems like not too bad a lift. I'd suggest going ahead with marking them as deprecated.
