### ISSUE TITLE
Enhancement: Add docstring for constructor for Identified class

### ISSUE THREAD

**Issue by rpgoldman** [SynBioDex/pySBOL3#321]
It would be helpful to have documentation about the initialization parameters:

```
identity: str, type_uri: str, *, name: str = None, description: str = None, derived_from: List[str] = None, generated_by: List[str] = None, measures: List[sbol3.object.SBOLObject] = None
```

Also, I note that the docstring shows:

```
Identified(... parameters ...) -> None
```

Shouldn't that be:

```
Identified(... parameters ...) -> Identified
```
?

**Comment by tcmitchell** [comment]
@rpgoldman A lot of the detailed documentation is lacking and this is a very good place to begin. Thanks for this request.

To your second point, about the return type of `Identified.__init__`, it should be `None`, as it is now, according to [PEP 484 -- Type Hints](https://www.python.org/dev/peps/pep-0484/). See the parenthetical note in https://www.python.org/dev/peps/pep-0484/#the-meaning-of-annotations
