### ISSUE TITLE
Validation treats missing TopLevel objects as errors

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#348]
SBOL allows TopLevel objects to be in documents that do not also contain all of their references. Our SHACL check for rule sbol3-10113, however, requires that the object be in the document.

Here is a minimal test case that demonstrates the issue:
```
doc = sbol3.Document()
doc.read('package.nt')
assert len(doc.validate()) == 0

minidoc = sbol3.Document()
c = doc.find('https://synbiohub.org/public/igem/BBa_I20270')
c.copy(minidoc)
assert len(doc.validate()) == 0  # this assertion fails
```
[package.nt.txt](https://github.com/SynBioDex/pySBOL3/files/7478277/package.nt.txt)

**Comment by jakebeal** [comment]
This appears to be inherent in the nature of the semi-closed generator on https://github.com/sparna-git/owl2shacl/blob/main/owl2sh-semi-closed.ttl

The fix would be to make our own generator that has an "or" case for TopLevel objects, such that they are allowed to have either the correct type or not be in the file at all.

**Comment by bbartley** [comment]
In the minimal test case above, should the last line should be?
```
assert len(minidoc.validate()) == 0  # this assertion fails
```
The difference being, validating `minidoc` rather than `doc`?

**Comment by jakebeal** [comment]
Whoops, yes; I was editing as I pasted and made a mistake there

**Comment by bbartley** [comment]
@jakebeal I might have a fix for this.  However, there may be a case where it doesn't work -- if a child  of `TopLevel: A` object references a child object of `TopLevel: B`.  Do we have any linkages of this sort in the data model?

**Comment by jakebeal** [comment]
`ComponentReference` definitely does this.  I'm not sure if there are any others off the top of my head.
