### ISSUE TITLE
JSONLD serialization includes bogus context

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/pySBOL3#349]
The JSONLD serialization of SBOL documents includes a bogus context entry that points to a broken link:
 "@vocab": "https://sbolstandard.org/examples/"

Minimal reproduction:
```
doc2 = sbol3.Document()
print(doc2.write_string(sbol3.JSONLD))
{
  "@context": {
    "@om": "http://www.ontology-of-units-of-measure.org/resource/om-2/",
    "@prov": "http://www.w3.org/ns/prov#",
    "@sbol": "http://sbols.org/v3#",
    "@vocab": "https://sbolstandard.org/examples/"
  },
  "@graph": []
}
```

**Comment by tcmitchell** [comment]
You're right. This is a holdover from the original JSONLD files in SBOLTestSuite. The `@vocab` was removed in SBOLTestSuite in SynBioDex/SBOLTestSuite@1b7e34ea9fb196eefc7c2ac391c5c304f15f9819. This can be removed from pySBOL3. It appears in `sbol3/document.py`.
