### ISSUE TITLE
doc.add does not work for lists when installed by pip install sbol3

### ISSUE THREAD

**Issue by Gonza10V** [SynBioDex/pySBOL3#352]
I have been using  pySBOL3 to create SBOL documents. Following the example of  doc.add() it dos not work for lists as stated on the circuit example (https://github.com/SynBioDex/pySBOL3/blob/main/examples/circuit.py). I wanted to contribute a function to add all but the implementation of that was already on the repository. Apparently it is not part of the package that I installed using pip install sbol3. To test that the add function works for lists I cloned the repo and installed it locally using pip install -e . on the masterbranch.

**Comment by tcmitchell** [comment]
It sounds like you might be using an older version of pySBOL3. What version are you using? Here's how to check:

```python
>>> import sbol3
>>> sbol3.__version__
'1.0b10'
>>> 
```

['Document.add' should support lists](https://github.com/SynBioDex/pySBOL3/issues/311) was added in [version 1.0b9](https://github.com/SynBioDex/pySBOL3/releases/tag/v1.0b9).

**Comment by Gonza10V** [comment]
Yes probably I had an old version pf pySBOL3 now I got version '1.0b10' using pip install sbol3 and '1.0b11' cloning the repository. Both having the document.add supporting lists.
