### ISSUE TITLE
Unable to use document.find() by name 

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/pySBOL3#38]
I have an SBOL Document with a Namespace object added to the document. 
If I want to get the added namespace by using the find() method, I can get the object by its URI but not by name. 
The find() method's documentation indicates the method operates using URI. Could someone check my code below if I have set this up right. If the code is valid, then the method's documentation should be updated to match its current behavior. 

https://github.com/SynBioDex/pySBOL3/blob/3d1ad4a18b44dda3575d2b86ffd01d6455a94040/sbol3/document.py#L175

Here is a sample code set up for testing. You can assume `ip_constants.SD2_UR="http://foo.com"`:
```
    def test_find_namespace_by_name(self):
        document = Document()
        namespace1 = Namespace(name=sbol_constants.SBOL3_NS, type_uri=ip_constants.SD2_URL)
        document.add(namespace1)
        actual_namespace1 = document.find(sbol_constants.SBOL3_NS)
        self.assertEqual(namespace1, actual_namespace1)

    def test_find_namespace_by_uri(self):
        document = Document()
        namespace1 = Namespace(name=sbol_constants.SBOL3_NS, type_uri=ip_constants.SD2_URL)
        actual_namespace1 = document.find(ip_constants.SD2_URL)
        self.assertEqual(namespace1, actual_namespace1)
```

**Comment by tcmitchell** [comment]
When `Document.find` is documented it should be clear that `search_string` can be either an entity's identity (a URI) or an entity's display_id (a string and not a URI).

The cited comment is not intended to serve as method documentation. It is intended to serve as a reminder to the programmer that search_string might be one of two different kinds of things.

**Comment by tcmitchell** [comment]
`Document.find` now has a doc comment that clarifies that `search_string` must be an object's `identity` or `display_id`.

I think this task is complete. Please reopen if more needs to be done.
