### ISSUE TITLE
Make Toplevel.copy() deprecation warning more informative

### ISSUE THREAD

**Issue by rpgoldman** [SynBioDex/pySBOL3#394]
Here's an example of the warning emitted by [this line](https://github.com/SynBioDex/pySBOL3/blob/5ae15b4f171991b3cd216b7548ffde7902f41c12/sbol3/toplevel.py#L176):

    /object.py:101: DeprecationWarning: Use sbol3.copy() instead
    warnings.warn('Use sbol3.copy() instead', DeprecationWarning)

Suggest the deprecation warning should say what is being deprecated.  Propose this modification:

    warnings.warn('Toplevel.copy() is deprecated; use sbol3.copy() instead', DeprecationWarning)

**Comment by Omarelsherif010** [comment]
#### This seems better. I will go with this issue and implement your suggested modification
@tcmitchell Do I need to be assigned to the issue or I can work on it right away?

**Comment by tcmitchell** [comment]
@Omarelsherif010 I have assigned this to you. Thanks for picking it up!

**Comment by Omarelsherif010** [comment]
I think we should close this issue now

**Comment by tcmitchell** [comment]
> I think we should close this issue now

Yes!
