### ISSUE TITLE
Differences between ReferencedObjects and URIProperty

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#4]
While these properties are similar in that they both store URIs as values, there are some specializations associated with each one.  I am listing one here, and I'll add more as I can recall them.
1.  Each URIProperty should be configurable to work with a particular ontology to allow automated look up of terms.  For example, the Component.roles property should be associated with SequenceOntology. This will enable automated look of terms and URIs.
2.  When performing copy operations that import and export objects into new namespaces, the URIs of ReferencedObjects should be modified according to the new namespace, while URIs of URIProperties (ontology terms) should be left alone

**Comment by tcmitchell** [comment]
We brainstormed on this a bit. It should be possible to add a `lookup()` method to the returned URI string so that a user could do something like:

```
component.model[0].lookup()
```

`component.model[0]` gives a `str` that is the URI. The lookup method will then look that URI up in the associated document.

**Comment by tcmitchell** [comment]
The `Component.roles` property is not exclusively associated with [SequenceOntology](http://www.sequenceontology.org).  One of the examples cited in the [SBOL 3 specification](https://sbolstandard.org/wp-content/uploads/2020/04/SBOL3.0specification.pdf) is "Effector" from the [ChEBI](https://registry.identifiers.org/registry/chebi) namespace.

**Comment by jakebeal** [comment]
That is correct; there are a set of recommended ontologies associated with particular `Component.type` values. Both `Component.role` and `Component.type` are open ranges, however, and can have any role, including novel custom roles in novel namespaces.

**Comment by tcmitchell** [comment]
Referenced objects are in, and on retrieval have the `lookup()` method above.

I don't know what to do with the original two items on this issue: shorthand for ontologies and changing URIs on copying.

**Comment by jakebeal** [comment]
Per discussion, the original two items are now moot.
