### ISSUE TITLE
Cannot extend `Location` as a `CustomIdentified`

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/pySBOL3#414]
`Location` invokes its super `__init__` method with positional arguments instead of keyword arguments. This does not work when a custom Location type is defined.

Here is a custom location type:
```python
class CustomLocationClass(sbol3.Location, sbol3.CustomIdentified):
    def __init__(self, sequence: Union[sbol3.Sequence, str],
                 *, type_uri=PYSBOL3_CUSTOM_LOCATION, identity=None):
        super().__init__(sequence=sequence, type_uri=type_uri, identity=identity)
        # Also test the int list while we're here
        self.foo_int = sbol3.IntProperty(self, PYSBOL3_CUSTOM_INT,
                                         0, math.inf)
```

When the above class is instantiated, like this:
```python
        seq = sbol3.Sequence('my_seq', elements='atcg')
        custom_loc = CustomLocationClass(sequence=seq)
```

The following exception is raised:
```python
Error
Traceback (most recent call last):
  File "/Users/tmitchel/Projects/sd2/pySBOL3/test/test_custom.py", line 182, in test_constructor
    custom_loc = CustomLocationClass(sequence=seq)
  File "/Users/tmitchel/Projects/sd2/pySBOL3/test/test_custom.py", line 40, in __init__
    super().__init__(sequence=sequence, type_uri=type_uri, identity=identity)
  File "/Users/tmitchel/Projects/sd2/pySBOL3/sbol3/location.py", line 21, in __init__
    super().__init__(identity, type_uri)
TypeError: CustomIdentified.__init__() takes from 1 to 2 positional arguments but 3 were given
```

The root cause is that `Location` uses positional arguments for the super constructor call instead of keyword arguments. These positional arguments work with `Identified` and not with `CustomIdentified`. Using keyword arguments fixes the problem.

**Comment by NehaAr** [comment]
import sbol3
class CustomLocationClass(sbol3.Location, sbol3.CustomIdentified):
    def __init__(self, sequence=sbol3.Sequence('my_seq', elements='atcg'),
                 *, type_uri=PYSBOL3_CUSTOM_LOCATION, identity=None'):


        
             self.foo_int = sbol3.IntProperty(PYSBOL3_CUSTOM_INT,
                                         0, math.inf)




//Calling the class
 custom_loc = CustomLocationClass()

Tried this and it worked. I removed the super as it is not that necessary and supplied eyword argments to init
