### ISSUE TITLE
Write unit test for feature.py validate function

### ISSUE THREAD

**Issue by Omarelsherif010** [SynBioDex/pySBOL3#420]
Hi @tcmitchell,

I have been working through current tests to make sure they apply all validation rules that are already implemented in the validation function inside classes, I noticed that feature class validate function doesn't have a unit test for its validation function so I am asking to start working on implementing this in preparation to work on "[Implement pySBOL3 Validation Rules](https://github.com/nrnb/GoogleSummerOfCode/issues/182)" project in GSoC.

I followed Jake's recommendation on preparation. After reading [SBOL Specification for Sequence class](https://sbolstandard.org/docs/SBOL3.0.1.pdf) Page 70, I have created sbol file to test different cases of validation function in sequence class. [link](https://github.com/Omarelsherif010/pySBOL3/tree/test-validation-behavior) to my fork (contains the file)

![test_validation_sequence_rules](https://user-images.githubusercontent.com/43929183/216829497-02959f40-0232-48b9-a579-2c028a2d37a6.png)

Then I checked the location class and feature class and noticed that the feature class doesn't have a unit test for its validation function. 
I remember you are using Test Driven Development in building the library so I plan to use it while implementing validation rules that have not yet been implemented. 

Do you recommend coding that unit test for the feature class validation function? or is there something better to do in preparation to implement other rules?

**Comment by tcmitchell** [comment]
@Omarelsherif010 yes, adding a unit test is a good first step towards implementing validation checks for the `Feature` class.
I will be happy to answer further questions, but my replies may be a little bit slow. I'm sorry in advance for the delays in responding to you.

**Comment by tcmitchell** [comment]
Closed by #426
