### ISSUE TITLE
'simple_library.nt' not present in the examples directory for it to be accessed by 'getting_started.ipynb' file

### ISSUE THREAD

**Issue by Atishaysjain** [SynBioDex/pySBOL3#446]
While running the file 'getting_started.ipynb' which is present in the 'examples' folder, I encountered an error while executing the 3rd cell:
```Shell
doc.read('simple_library.nt')
```
It turns out the file 'simple_library.nt' is not present in the 'examples' folder. The file 'simple_library.nt' is present in '/test/resources' folder. There are two simples fix to this issue:

(i) Add the file 'simple_library.nt' file to the examples folder. OR
(ii) Changing the third cell from
```Shell
doc.read('simple_library.nt')
```
to
```Shell
doc.read(os.path.join('..', 'test', 'resources', 'simple_library.nt'))
```
The os library is already imported in the first cell of the python notebook.

I can create a pull request with either of the solutions @jakebeal. Thank You.

**Comment by jakebeal** [comment]
I like the second option better. It would better yet if it used pathlib.Path rather than os.path.join, which can look something like: `doc.read(Path.cwd().parent / 'test' / 'resources' / 'simple_library.nt')`

**Comment by Atishaysjain** [comment]
Understood, thanks a lot.

**Comment by tcmitchell** [comment]
I'm terribly sorry it has taken so long to merge this PR. Thanks for submitting!
