### ISSUE TITLE
Signature overloading should be allowed in some special, but limited cases

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#5]
In general, signature overloading should be avoided, but there are at least 2 cases where it is helpful:
1. Constructors - creation using a URI vs. a displayId

`cd = ComponentDefinition(URI('http://bbn.com/foo'), ...)`

 vs.

 `cd = ComponentDefinition('foo')`

2. URIProperties - assignment using URIs vs. strings

 `cd.roles = URI('http://identifiers.org/000000')`

 vs.

`cd.roles = 'misc_feature'`

**Comment by tcmitchell** [comment]
1. Constructors - creation using a URI vs. a displayId
    * This is handled. An entity can be created with either a full identity (i.e. URI/URL) or with a displayId. The displayId is appended to the homespace, as was done in pySBOL and pySBOL2, to form the identity.
2. URIProperties - assignment using URIs vs. strings
    * There is no URI type, so the example doesn't match - we only use strings
    * Referenced object properties can be set using a URI or using an Identified, which is fairly similar

**Comment by tcmitchell** [comment]
This appears to be complete.
