### ISSUE TITLE
Automated lookup of ontology terms

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#6]
URIs of URIProperty assignments should be automatically assigned through lookup of the associated natural language term.  

For example:
`cd.roles = ['promoter']`
Should assign:
`cd.roles = [URI('http://identifiers.org/0000167')]`

This also requires that each URIProperty knows which ontology it is associated with.  See #4

**Comment by jakebeal** [comment]
I think this may be fulfilled by TYTO, but we should figure out whether that should be automatically included with pySBOL3 or just in the documentation.

**Comment by jakebeal** [comment]
@tcmitchell Can you consider this and make a recommendation of how to bundle TYTO with pySBOL3 (or not)?

**Comment by tcmitchell** [comment]
I think sbol3 should be usable with or without TYTO. We should try to verify that the two packages can safely coexist without sbol3 depending on TYTO. I don't know of a reason why the two modules would not be compatible. I can test this out and include some documentation.

**Comment by jakebeal** [comment]
I'm certainly having no issues using the two together.

Accordingly, I'd suggest resolving this with:
1. Add a CI test that uses TYTO
2. Recommend use of TYTO in the documentation and add some examples of its use to the tutorial material, etc.
