### ISSUE TITLE
Change Component.identity  to use a different namespace

### ISSUE THREAD

**Issue by tramyn** [SynBioDex/pySBOL3#62]
When creating a protein using the library's Component class, an identity field is automatically set to take on the form of "http://example.com/sbol3/bGM_337". I don't think the namespace "http://example.com/sbol3/" is meaningful and would like to change it to "http://sbols.org/sbol3/bGM_337". I tried looking through sbol3's specification to see if users are allowed to edit the identity field or if this is something that the library will have control over. Unfortunately, I was unable to locate this information in the spec. to indicate how this should be handled. Since this is the case, could the library change the namespace of a Component. identity to have more meaningful value? 

Here is sample code to test this feature:
```
    def test_create_protein(self):
        document = Document()
        protein_bGM_337 = 'bGM_337'
        input_protein = Component(name=protein_bGM_337, component_type=sbol_constants.SBO_PROTEIN)
        protein_identity = 'http://sbols.org/sbol3/%s' % protein_bGM_337
        input_protein.identity = protein_identity
        document.add(input_protein)

        output_protein = document.find(protein_bGM_337)
        self.assertEqual(input_protein, output_protein)
        self.assertEqual(protein_bGM_337, output_protein.display_id)
        self.assertEqual(protein_identity, output_protein.identity)
        self.assertEqual(sbol_constants.SBOL_COMPONENT, output_protein.type_uri)
        self.assertEqual([sbol_constants.SBO_PROTEIN], output_protein.types)
```

**Comment by tcmitchell** [comment]
Thanks for being a patient alpha tester. You want to use `set_homespace()` to set the base URI, just like you would have used `setHomespace()` in sbol2. Here is an example:

```python
import sbol3

sbol3.set_homespace('http://sbols.org/sbol3')

document = sbol3.Document()
protein_bGM_337 = 'bGM_337'
input_protein = sbol3.Component(protein_bGM_337, sbol3.SBO_PROTEIN)
print(input_protein.identity)
document.add(input_protein)
```

The output is:

```
http://sbols.org/sbol3/bGM_337
```

Please know that you're not supposed to use `http://sbols.org` because that's not a domain under your control. You should choose something related to your project, or related to a domain name you control, like `https://github.com/tramyn`. See Section 5.2 of the spec.

**Comment by tcmitchell** [comment]
Sorry - it's in Section 5.2 in an upcoming version of the spec. The new Section 5.2 is titled "SBOL URIs" and says:

> The SBOL namespace, which is http://sbols.org/v3#, is used to indicate which entities and properties in an SBOL document are defined by SBOL. For example, the URI of the type Component is http://sbols.org/v3#Component. This convention is assumed throughout the specification. The SBOL namespace MUST NOT be used for any entities or properties not defined in this specification.

**Comment by tcmitchell** [comment]
@tramyn can this issue be closed or are there things that still need to be fixed?

**Comment by tramyn** [comment]
@tcmitchell Fine with closing.
