### ISSUE TITLE
Annotation property cannot be accessed after round trip

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#76]
I recommend supporting the following pattern for accessing annotation properties:
```
    def test_annotation(self):
        # Create custom annotation
        c = sbol3.Component('c1', sbol3.SBO_DNA)
        c.annotation = sbol3.TextProperty(c, 'http://example.org/boolean_property', 0, 1, [])
        c.annotation = 'foo'
        doc = sbol3.Document()
        doc.add(c)
        doc.write('foo.xml', file_format='xml')

        # Roundtrip
        doc = sbol3.Document()
        doc.read('foo.xml', file_format='xml')

        # Recover annotation
        c = doc.find('c1')
        c.annotation = sbol3.TextProperty(c, 'http://example.org/boolean_property', 0, 1, [])
        self.assertEqual(c.annotation, 'foo')
```
This currently fails with:
```
======================================================================
FAIL: test_annotation (test.test_property.TestProperty)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bbartley/Dev/git/pySBOL3/test/test_property.py", line 73, in test_annotation
    self.assertEqual(c.annotation, 'foo')
AssertionError: None != 'foo'
```

**Comment by tcmitchell** [comment]
Can you tell where the annotation gets lost? Is it written to file? Is it read from file?

I note that you don't check the value after setting it initially. Is it broken there as well? (Meaning between `c.annotation = 'foo'` and `doc = sbol3.Document()` around line 5 of your example)

**Comment by bbartley** [comment]
The annotation value can be accessed when it is assigned, and it is serialized to the output file.  It's only upon reading the file in that the annotation data is lost.

**Comment by tcmitchell** [comment]
The value was being overwritten when the annotation property was created after the round trip. A modified version of the test in the description has been added to the module test suite.
