### ISSUE TITLE
Can `read` and `write` methods infer the file format?

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#77]
Can the `read` and `write` methods infer the RDF file format from the file extension?

For example:
```
doc.write('foo.xml')
```
Currently the user is explicitly required to declare the file format:
```
doc.write('foo.xml', file_format='xml')
```

**Comment by tcmitchell** [comment]
Sure, in cases where it is clear. What is the desired behavior when the extension is unclear, like `doc.write('foo.sbol')` and `doc.read('foo.sbol')`?

Also, there are constants for the file format: `sbol3.RDF_XML`, for instance. The benefit to requiring a file format is to make it [explicit rather than implicit](https://www.python.org/dev/peps/pep-0020/#id2).

**Comment by bbartley** [comment]
In the case that a user provides a standard file extension,  I would argue that simply providing a filename with a standard extension _is_ explicit, and therefore in spirit of PEP20.  Whereas `doc.write('foo.xml', file_format='xml')` is simply redundant, repetitious, and redundant.  Philosophy aside, it's just easy for me to forget the `file_format` argument and I am going to be tripping over this constantly.  I think we are all used to applications inferring file types from the file extensions.

In the case that it is not a standard file extension, e.g., xml, ttl, nt, then absolutely the `file_format` should be required.  Probably the user should get an error message that says ("File format {extension} not recognized.  Please use the file_format keyword to specify a file format").

**Comment by tcmitchell** [comment]
We can use [rdflib.util.guess_format](https://rdflib.readthedocs.io/en/stable/apidocs/rdflib.html#rdflib.util.guess_format):

```python
>>> import rdflib
RDFLib Version: 5.0.0
>>> rdflib.util.guess_format
<function guess_format at 0x7fd47848cf70>
>>> help(rdflib.util.guess_format)

>>> rdflib.util.guess_format('data.nt')
'nt'
>>> rdflib.util.guess_format('data.rdf')
'xml'
>>> rdflib.util.guess_format('data.ttl')
'turtle'
>>> rdflib.util.guess_format('data.xml')
>>> rdflib.util.guess_format('data.xml') == None
True
```

The return value is not documented. It looks like `None` is returned if the file extension is not recognized.
