### ISSUE TITLE
OwnedObject has no type checking

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/pySBOL3#86]
For properties involving child objects, there doesn't seem to be any type checking, so I can add certain types of objects where it doesnt make sense.

**Comment by bbartley** [comment]
To elaborate on this, below is an example of an assignment that I believe should generate a `TypeError`.  The `features` attribute should only allow assignment of `Features` or subclasses thereof.  Assignment with a `Range` should generate a type error.
```
>>> c = sbol3.Component('foo', sbol3.SBO_DNA)
>>> c.features = [ sbol3.Range('bar', 1, 2) ]
>>> c.features
[<sbol3.location.Range object at 0x102e8abd0>]
```
I believe that type checking can be supported by modifying the `OwnedObject` constructor, which should accept the expected type of the child object as a parameter:
```
self.features = OwnedObject(self, SBOL_FEATURES, sbol3.Feature, 0, math.inf)
```
The setter can then check whether the assigned object is a Feature or subclass.

**Comment by tcmitchell** [comment]
I think we want to handle this in `OwnedObjectPropertyMixin.from_user` so it takes effect across the full range of assignment options.
