### ISSUE TITLE
Consider requiring a call to set_namespace

### ISSUE THREAD

**Issue by tcmitchell** [SynBioDex/pySBOL3#99]
pySBOL3 has a default namespace. If no action is taken by the programmer that namespace is used to build identities for objects when only a display_id is given.

A suggestion at [COMBINE 2020](http://co.mbine.org/events/COMBINE_2020) was require the user to set a namespace so that they have to take positive action and won't use an arbitrary default namespace.

Should pySBOL3 use a default namespace, or should pySBOL3 require the programmer to set a namespace in their program?

**Comment by jakebeal** [comment]
I'd suggest that we not allow a pre-initialized default namespace.  I think we can use any mixture of:
- Allow the user to set a working namespace, which TopLevel objects are then created in.
- Allow the user to explicitly specify a namespace when creating a TopLevel object.
